version: '3'

volumes:
  appdata:
  mariadb_data:

networks:
  internal: ~

services:
  nginx:
    build:
      context: ../
      dockerfile: docker/local/nginx/Dockerfile
      args:
        FASTCGI_PASS: php
    ports:
      - 8080:80
    networks:
      - internal
    depends_on:
      - php
    volumes:
      - appdata:/var/www/html/var/logs
      - appdata:/var/www/html/var/cache
      - ../:/var/www/html:cached

  php:
    build:
      context: ../
      dockerfile: docker/local/php/Dockerfile
    networks:
      - internal
    volumes:
      - appdata:/var/www/html/var/logs
      - appdata:/var/www/html/var/cache
      - ../:/var/www/html:cached

  mariadb:
    image: mariadb:10.3.22
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: root